### ISSUE TITLE
프로젝트 초기 설정 및 개발 도구 설치

### ISSUE THREAD

**Issue by neptune588** [neptune588/Picket-FE#1]
## ISSUE

본격적인 프로젝트 개발을 위해 
개발 도구 설치 및 설정을 합니다.

## TODO

- [x] VITE 설치 및 셋팅
- [x] STYLED-COMPONENT, AXIOS등 기타 라이브러리 설치 
- [x] REACT-ROUTER 설치
- [x] 절대경로 설정
