### ISSUE TITLE
화면 구성(홈, 프로필, 알람)

### ISSUE THREAD

**Issue by Mulverry** [neptune588/Picket-FE#10]
## ISSUE

홈화면, 프로필 화면, 알람화면을 구현합니다.

## TODO

- [x] 메인홈 화면 구성
- [x] 이미지 업로드 화면 구성
- [x] 알림, 공개 설정(캘린더)
- [x] 버킷모달
- [x] 프로필 화면 구성
- [x] 프로필 모달
- [x] 알람화면 구성

**Comment by Mulverry** [comment]
commit 메시지 작성하는 과정에서 뭔가가 잘못 되었습니다. 최종본으로 확인하시면 됩니다
