### ISSUE TITLE
탐색페이지 레이아웃 제작 및 /로그인+로그아웃 보완/ 검색모달 레이아웃 제작

### ISSUE THREAD

**Issue by neptune588** [neptune588/Picket-FE#17]
## ISSUE

탐색 페이지 레이아웃을 제작합니다.
더불어 로그인/로그아웃 기능을 약간 보완합니다.

## TODO

- [x] 탐색 페이지 레이아웃 제작
- [x] 로그인/로그아웃 기능 보완, 비밀번호 찾기 페이지 제작
- [x] 검색 모달 제작
