### ISSUE TITLE
버킷 상세보기

### ISSUE THREAD

**Issue by Mulverry** [neptune588/Picket-FE#20]
## ISSUE

버킷 상세보기

## TODO
- [x] 무한스크롤
- [x] 마이 버킷을 눌렀을 때 상세보기 모달이 열림
- [x] 좋아요, 스크랩 버튼 작동 및 프로필 스크랩 화면과 연동
- [x] 댓글 작성
- [ ] 버킷 달성, 보류, 수정, 삭제

**Comment by neptune588** [comment]
이슈 종료하겠습니다 _ _
