### ISSUE TITLE
프로필 페이지 제작 및 버킷 삭제, 달성 기능 추가

### ISSUE THREAD

**Issue by neptune588** [neptune588/Picket-FE#26]
## ISSUE

프로필 페이지 제작 및 버킷 삭제, 달성 기능을 추가한다.

## TODO

- [x] 버킷 삭제 기능 추가
- [x] 버킷 달성 기능 추가
- [x] 프로필 페이지 제작
