### ISSUE TITLE
디렉토리 구조 생성 및 스타일드 컴포넌트, 리액트 라우터 셋팅

### ISSUE THREAD

**Issue by neptune588** [neptune588/Picket-FE#3]
## ISSUE

제작에 앞서 필요한 디렉토리를 구조화 합니다.
스타일드 컴포넌트와 react-router-dom 셋팅을 합니다.

## TODO

- [x] 디렉토리 용도에 맞게 구조화
- [x] Styled-Components 셋팅
- [x] React-router-dom 셋팅
