### ISSUE TITLE
회원가입 페이지 구현 및 로그인 페이지 목업

### ISSUE THREAD

**Issue by neptune588** [neptune588/Picket-FE#8]
## ISSUE

회원가입 페이지를 구현합니다.

로그인 페이지 목업을 만듭니다.

목업 -> 기능구현 순서로 진행을 하며

배경지식이 거의 전무한 수준이기에, 시간이 오래 걸릴걸로 예상됩니다.

## TODO

- [x] 공통 INPUT 컴포넌트 제작
- [x] 회원가입 페이지 목업
- [x] 로그인 페이지 목업
- [x] 회원가입 기능구현
- [x] axios 인스턴스 생성
- [x] 리액트쿼리 default 셋팅
- [x] 로딩 컴포넌트 제작

**Comment by neptune588** [comment]
close
